WebApplication1/Models/Person.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public class Person
    {
        [Key]
        [Required]
        public int ID { get; set; }

        [Required(ErrorMessage = "Title is required")]
        [Display(Name = "Title")]
        [StringLength(6, MinimumLength = 2)]
        public string Title { get; set; }

        [Required(ErrorMessage = "First Name is required")]
        [StringLength(100, MinimumLength = 2)]
        public string ForeName { get; set; }

        [Required(ErrorMessage = "Last Name is required")]
        [StringLength(100, MinimumLength = 2)]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Address is required")]
        [StringLength(100, MinimumLength = 2)]
        public string Address { get; set; }

        [Required(ErrorMessage = "Phone is required")]
        [StringLength(100, MinimumLength = 2)]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Date of Birth is required")]
        [StringLength(100, MinimumLength = 2)]
        public string DOB { get; set; }

        public string Avatar { get; set; }

       

        public Person() { }
    }

    public class PersonList
    {
        public List<Person> personList { get; set; }

        public PersonList()
        {
           
        }

        

        

      
       
    }

    
    public class PersonDBContext: DbContext
    {
        public DbSet<Person> PersonList
        {
            get; set;
        }
    }

        

   
}

WebApplication1/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class PeopleController : Controller
    {
        private WebApplication1Context db = new WebApplication1Context();

        // GET: People
        public ActionResult Index()
        {
            return View(db.People.ToList());
        }

        // GET: People/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // GET: People/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,ForeName,LastName,Address,Phone,DOB,Avatar")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.People.Add(person);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(person);
        }

        // GET: People/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,ForeName,LastName,Address,Phone,DOB,Avatar")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(person);
        }

        // GET: People/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Person person = db.People.Find(id);
            db.People.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class PersonController : Controller
    {
        public PersonDBContext _dbContext;

       

        // GET: Form
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Store(Person person)
        {
  
            return Json(person);
        }

        public ActionResult Edit(int id = 0)
        {
            var person = _dbContext.PersonList.First(x => x.ID == id);
            return View(person);
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            return RedirectToAction("index");
        }

      
    }
}

WebApplication1/Views/Person/Create.cshtml
@model WebApplication1.Models.Person

@{
    ViewBag.Title = "create";
}

<h2>Add the pet's owner</h2>

<div id="form">

</div>

@using (Html.BeginForm("Store", "Person", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div class="form-group">
        @Html.LabelFor(p => p.Title, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(p => p.Title, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(p => p.ForeName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(p => p.ForeName, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(p => p.LastName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(p => p.LastName, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(p => p.Address, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(p => p.Address, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(p => p.Phone, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(p => p.Phone, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(p => p.DOB, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(p => p.DOB, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(p => p.Avatar, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <input asp-for="FileUpload.UploadPrivateSchedule" type="file" class="form-control" style="height:auto" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Add" />
        </div>
    </div>
}

@section scripts{
    <script src="~/Scripts/reactjs/dist/bundle.js"></script>
}

WebApplication1/Views/Person/Edit.cshtml
@model WebApplication1.Models.Person
@{
    ViewBag.Title = "Edit Info";
}

<h2>Edit Info</h2>


@using (Html.BeginForm("Store", "Person", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div class="form-group">
        @Html.LabelFor(p => p.Title, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(p => p.Title, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(p => p.ForeName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(p => p.ForeName, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(p => p.LastName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(p => p.LastName, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(p => p.Address, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(p => p.Address, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(p => p.Phone, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(p => p.Phone, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(p => p.DOB, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(p => p.DOB, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(p => p.Avatar, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <input asp-for="FileUpload.UploadPrivateSchedule" type="file" class="form-control" style="height:auto" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Update" />
        </div>
    </div>
}

WebApplication1/Views/Person/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<h2>title</h2>

<table border="1">
    <tr>
        <th>Title</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Address</th>
        <th>Phone</th>
        <th>DOB</th>
        <th>Picture</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Title</td>
            <td>@item.ForeName</td>
            <td>@item.LastName</td>
            <td>@item.Address</td>
            <td>@item.Phone</td>
            <td>@item.DOB</td>
            <td><img src="@item.Avatar" /> </td>
        </tr>
    }

</table>